### ISSUE TITLE
Bug: Have to open app twice to start

### ISSUE THREAD

**Issue by joshpetit** [OrangeDrangon/android-messages-desktop#350]
Thanks a lot for maintaining this :)

**Describe the bug**
When you first open the app you have to reopen it to get it to run

**To Reproduce**
1. Open app
2. See this error:
```
Checking for update
Error: Error: ENOENT, dev-app-update.yml not found in /usr/lib/android-messages-desktop/resources/app.asar
    at createError (electron/js2c/asar_bundle.js:5:1255)
    at e.readFile (electron/js2c/asar_bundle.js:5:8025)
    at go$readFile (/usr/lib/android-messages-desktop/resources/app.asar/node_modules/graceful-fs/graceful-fs.js:118:14)
    at readFile (/usr/lib/android-messages-desktop/resources/app.asar/node_modules/graceful-fs/graceful-fs.js:115:12)
    at /usr/lib/android-messages-desktop/resources/app.asar/node_modules/universalify/index.js:10:14
    at new Promise (<anonymous>)
    at readFile (/usr/lib/android-messages-desktop/resources/app.asar/node_modules/universalify/index.js:7:14)
    at AppImageUpdater.loadUpdateConfig (/usr/lib/android-messages-desktop/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:602:67)
    at Lazy.<anonymous> (/usr/lib/android-messages-desktop/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:211:58)
    at Lazy.get value [as value] (/usr/lib/android-messages-desktop/resources/app.asar/node_modules/lazy-val/out/main.js:23:25)
```
3. Open app again in another session
4. Enjoy

**Expected behavior**
It'd be nice if it worked when being opened the first time, since right now I have to open it twice using rofi which messes up it's placing on the priority list. I'll likely change the run command to run twice to get it to work.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version 5.2.1-1

**Additional context**

**Comment by OrangeDrangon** [comment]
How did you install the program? I assume the AUR but which AUR version?

**Comment by joshpetit** [comment]
@OrangeDrangon I installed the binary version

**Comment by dawaltconley** [comment]
think I have a similar problem on Pop OS from the latest deb install. Same effect (have to open twice) and when running `/opt/AndroidMessages/AndroidMessages` I get
```
Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/AndroidMessages/resources/app-update.yml'
```
I _do_ have app.asar in resources though. :)
